adb devices
adb shell pm enable android.autoinstalls.config.samsung
adb shell pm enable com.android.apps.tag
adb shell pm enable com.android.bips
adb shell pm enable com.android.bluetoothmidiservice
adb shell pm enable com.android.bookmarkprovider
adb shell pm enable com.android.carrierdefaultapp
adb shell pm enable com.android.chrome
adb shell pm enable com.android.dreams.basic
adb shell pm enable com.android.dreams.phototable
adb shell pm enable com.android.egg
adb shell pm enable com.android.hotwordenrollment.okgoogle
adb shell pm enable com.android.hotwordenrollment.xgoogle
adb shell pm enable com.android.internal.systemui.onehanded.gestural
adb shell pm enable com.android.managedprovisioning
adb shell pm enable com.android.providers.partnerbookmarks
adb shell pm enable com.android.sharedstoragebackup
adb shell pm enable com.android.stk
adb shell pm enable com.android.stk2
adb shell pm enable com.android.traceur
adb shell pm enable com.facebook.appmanager
adb shell pm enable com.facebook.services
adb shell pm enable com.facebook.system
adb shell pm enable com.google.android.apps.accessibility.voiceaccess
adb shell pm enable com.google.android.apps.carrier.carrierwifi
adb shell pm enable com.google.android.apps.messaging
adb shell pm enable com.google.android.apps.restore
adb shell pm enable com.google.android.apps.tachyon
adb shell pm enable com.google.android.apps.turbo
adb shell pm enable com.google.android.as
adb shell pm enable com.google.android.as.oss
adb shell pm enable com.google.android.cellbroadcastreceiver
adb shell pm enable com.google.android.feedback
adb shell pm enable com.google.android.gms.location.history
adb shell pm enable com.google.android.gms.supervision
adb shell pm enable com.google.android.onetimeinitializer
adb shell pm enable com.google.android.partnersetup
adb shell pm enable com.google.android.projection.gearhead
adb shell pm enable com.google.android.tts
adb shell pm enable com.google.ar.core
adb shell pm enable com.google.audio.hearing.visualization.accessibility.scribe
adb shell pm enable com.hiya.star
adb shell pm enable com.knox.vpn.proxyhandler
adb shell pm enable com.microsoft.appmanager
adb shell pm enable com.microsoft.skydrive
adb shell pm enable com.samsung.android.aircommandmanager
adb shell pm enable com.samsung.android.allshare.service.mediashare
adb shell pm enable com.samsung.android.app.camera.sticker.facearavatar.preload
adb shell pm enable com.samsung.android.app.clipboardedge
adb shell pm enable com.samsung.android.app.cocktailbarservice
adb shell pm enable com.samsung.android.app.omcagent
adb shell pm enable com.samsung.android.app.readingglass
adb shell pm enable com.samsung.android.app.reminder
adb shell pm enable com.samsung.android.app.routines
adb shell pm enable com.samsung.android.app.settings.bixby
adb shell pm enable com.samsung.android.app.taskedge
adb shell pm enable com.samsung.android.app.watchmanagerstub
adb shell pm enable com.samsung.android.appseparation
adb shell pm enable com.samsung.android.ardrawing
adb shell pm enable com.samsung.android.aremoji
adb shell pm enable com.samsung.android.aremojieditor
adb shell pm enable com.samsung.android.authfw
adb shell pm enable com.samsung.android.aware.service
adb shell pm enable com.samsung.android.bbc.bbcagent
adb shell pm enable com.samsung.android.beaconmanager
adb shell pm enable com.samsung.android.bixby.agent
adb shell pm enable com.samsung.android.bixby.wakeup
adb shell pm enable com.samsung.android.bixbyvision.framework
adb shell pm enable com.samsung.android.cidmanager
adb shell pm enable com.samsung.android.cmfa.framework
adb shell pm enable com.samsung.android.da.daagent
adb shell pm enable com.samsung.android.dkey
adb shell pm enable com.samsung.android.easysetup
adb shell pm enable com.samsung.android.emergency
adb shell pm enable com.samsung.android.fast
adb shell pm enable com.samsung.android.fmm
adb shell pm enable com.samsung.android.forest
adb shell pm enable com.samsung.android.game.gamehome
adb shell pm enable com.samsung.android.game.gametools
adb shell pm enable com.samsung.android.game.gos
adb shell pm enable com.samsung.android.ipsgeofence
adb shell pm enable com.samsung.android.kidsinstaller
adb shell pm enable com.samsung.android.knox.analytics.uploader
adb shell pm enable com.samsung.android.knox.attestation
adb shell pm enable com.samsung.android.knox.containercore
adb shell pm enable com.samsung.android.knox.kpecore
adb shell pm enable com.samsung.android.knox.pushmanager
adb shell pm enable com.samsung.android.mcfserver
adb shell pm enable com.samsung.android.mdecservice
adb shell pm enable com.samsung.android.mdx
adb shell pm enable com.samsung.android.mdx.kit
adb shell pm enable com.samsung.android.net.wifi.wifiguider
adb shell pm enable com.samsung.android.peripheral.framework
adb shell pm enable com.samsung.android.rubin.app
adb shell pm enable com.samsung.android.samsungpass
adb shell pm enable com.samsung.android.samsungpassautofill
adb shell pm enable com.samsung.android.service.livedrawing
adb shell pm enable com.samsung.android.service.peoplestripe
adb shell pm enable com.samsung.android.service.stplatform
adb shell pm enable com.samsung.android.smartcallprovider
adb shell pm enable com.samsung.android.smartmirroring
adb shell pm enable com.samsung.android.smartsuggestions
adb shell pm enable com.samsung.android.smartswitchassistant
adb shell pm enable com.samsung.android.spayfw
adb shell pm enable com.samsung.android.stickercenter
adb shell pm enable com.samsung.android.visionintelligence
adb shell pm enable com.samsung.android.visualars
adb shell pm enable com.samsung.app.newtrim
adb shell pm enable com.samsung.cmfa.AuthTouch
adb shell pm enable com.samsung.faceservice
adb shell pm enable com.samsung.klmsagent
adb shell pm enable com.samsung.knox.securefolder
adb shell pm enable com.samsung.safetyinformation
adb shell pm enable com.samsung.ssu
adb shell pm enable com.samsung.storyservice
adb shell pm enable com.sec.android.app.billing
adb shell pm enable com.sec.android.app.chromecustomizations
adb shell pm enable com.sec.android.app.magnifier
adb shell pm enable com.sec.android.app.myfiles
adb shell pm enable com.sec.android.app.quicktool
adb shell pm enable com.sec.android.app.safetyassurance
adb shell pm enable com.sec.android.app.wlantest
adb shell pm enable com.sec.android.autodoodle.service
adb shell pm enable com.sec.android.easyMover.Agent
adb shell pm enable com.sec.android.mimage.avatarstickers
adb shell pm enable com.sec.android.widgetapp.easymodecontactswidget
adb shell pm enable com.sec.android.widgetapp.webmanual
adb shell pm enable com.sec.epdgtestapp
adb shell pm enable com.sec.location.nsflp2
adb shell pm enable com.sec.mhs.smarttethering
adb shell pm enable com.sec.spp.push
adb shell pm enable com.wsomacp
adb shell pm enable de.axelspringer.yana.zeropage
adb shell pm enable com.instagram.android

adb shell pm enable com.google.android.apps.googleassistant
adb shell pm enable com.google.android.adservices.api
adb shell pm enable com.google.android.ondevicepersonalization.services

adb shell pm enable com.aura.oobe.samsung.gl
adb shell pm enable com.qualcomm.location
adb shell pm enable com.samsung.android.mobileservice
adb shell pm enable com.sec.android.daemonapp
adb shell pm enable com.samsung.android.app.parentalcare
adb shell pm enable com.samsung.android.rampart
adb shell pm enable com.samsung.android.sm.devicesecurity
adb shell pm enable com.samsung.android.mapsagent